package com.gamealition.DataHarvestor.Events;

/**
 * Created by robert on 03/01/2017.
 */
public enum EventType {
    PLAYER_BLOCK_PLACE,
    PLAYER_BLOCK_BREAK,
    PLAYER_SPAWNED_ENTITY,
    PLAYER_CHAT,
    PLAYER_JOIN,
    PLAYER_LEAVE,
    PLAYER_MOVE,
    PLAYER_SNEAK,
    PLAYER_DROP_ITEM,
    PLAYER_PICKUP_ITEM,
    PLAYER_TELEPORT,
    PLAYER_RESPAWN, PLAYER_LEAVE_BED, PLAYER_ENTER_BED, PLAYER_CHANGE_WORLD, PLAYER_DEATH, PLAYER_PORTAL, SERVER_META, PLAYER_STATS
}
